; InputAutoCfg.ini for Mupen64Plus SDL Input plugin

; Keyboard_START
[Keyboard]
plugged = True
plugin = 2
mouse = False
DPad R = key(100)
DPad L = key(97)
DPad D = key(115)
DPad U = key(119)
Start = key(13)
Z Trig = key(122)
B Button = key(306)
A Button = key(304)
C Button R = key(108)
C Button L = key(106)
C Button D = key(107)
C Button U = key(105)
R Trig = key(99)
L Trig = key(120)
Mempak switch = key(44)
Rumblepak switch = key(46)
X Axis = key(276,275)
Y Axis = key(273,274)
; Keyboard_END

; PS3 Controller_START 
[PS3 Controller]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
Mempak switch = 
Rumblepak switch = 
DPad L = button(15) 
DPad R = button(16) 
R Trig = button(5) 
DPad D = button(14) 
B Button = button(3) 
C Button U = button(2) 
A Button = button(0) 
C Button D = button(1) 
DPad U = button(13) 
Start = button(9) 
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)
Z Trig = button(4) 
; PS3 Controller_END 

