[PS3 Controller]
plugged = True
plugin = 2
mouse = False
AnalogDeadzone = 4096,4096
AnalogPeak = 32768,32768
Mempak switch = 
Rumblepak switch = 
DPad L = button(15) 
DPad R = button(16) 
R Trig = button(5) 
DPad D = button(14) 
B Button = button(3) 
C Button U = button(2) 
A Button = button(0) 
C Button D = button(1) 
DPad U = button(13) 
Start = button(9) 
X Axis = axis(0-,0+)
Y Axis = axis(1-,1+)
Z Trig = button(4) 
; PS3 Controller_END 

