# Enable dimming after <seconds>, between 1 and 3600
enable_dim=true
dim_seconds=300
# Enable fast mode (double input polling rate on atmega)
fast_mode=false
# Disable CRC checks
disable_crc=false
# Enable the gamepad or mouse
input_type=gamepad
# Set number of joysticks, where <num> is between 0 and 2
joysticks=1
# Set stick deadzone flat value (0-100, default: 20)
deadzone=20
# Use stick position at startup as center point
autocenter=false
# Enable verbose output (e.g. CRC errors)
verbose=false
# Enable extra buttons (trigger, stick, or disabled)
extrabuttons=disabled
