name: Build Drivers
description: 'Build PSPi drivers'
inputs:
  build:
    description: 'Comma seperated list of images to build'
    required: true
  createRelease:
    description: 'Create a release'
    default: 'false'
  version:
    description: 'gitversion version'
    required: true

runs:
  using: "composite"
  steps:
    # Install packer dependencies
    - name: Install dependencies
      run: |
        echo "Create release value is ${{ inputs.createRelease }}"
        sudo apt-get update
        sudo apt-get install fdisk gdisk qemu-system qemu-user-static libarchive-tools tar parted qemu-utils binfmt-support
      shell: bash

    # Build driver image
    - name: Build 64-bit driver image
      run: |
        sudo packer init ./
        sudo packer build -only "drivers.cross.drivers_raspios_lite_arm64" "$GITHUB_WORKSPACE/packer/"
      working-directory: packer
      shell: bash      

    # Extract drivers from image & zip for release
    - name: Extract drivers from image
      run: |
        mv *.tar.gz $RUNNER_TEMP
        cd $RUNNER_TEMP
        mkdir -p ./drivers

        # Extract & rename 64bit drivers
        tar --extract --file=PSPi6.Drivers_64bit.tar.gz ./packer/drivers/bin
        for i in $(ls ./packer/drivers/bin)
        do
          mv "./packer/drivers/bin/$i" "./drivers/${i}_64"
        done

        # Zip drivers
        zip drivers.zip ./drivers/* -r
      working-directory: packer
      shell: bash

    # Upload drivers as artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: drivers
        path: ${{ runner.temp }}/drivers/
        if-no-files-found: error

    # Create github release
    - name: Create Release
      if: github.ref == 'refs/heads/main' || inputs.createRelease == 'true'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ inputs.version }}
        name: v${{ inputs.version }}
        body_path: .github/workflows/RELEASE_FORMAT.txt
        draft: true
        fail_on_unmatched_files: true
        files: |
          ${{ runner.temp }}/drivers.zip