name: Build Audio Overlays

on:
  workflow_call:
  push:
    paths:
      - 'rpi/audio/**'
  pull_request:
    paths:
      - 'rpi/audio/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y device-tree-compiler make

      - name: Build overlays
        run: |
          cd rpi/audio
          make

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pspi-audio-overlays
          path: rpi/audio/*.dtbo
