name: Build Gamepad Binary

on:
  workflow_call:
  push:
    paths:
      - 'rpi/gamepad/**'
  pull_request:
    paths:
      - 'rpi/gamepad/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu make

      - name: Build
        run: |
          cd rpi/gamepad
          make 32
          make 64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pspi-gamepad-bin
          path: rpi/gamepad/bin/
