name: Build Images

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release Version'
        required: true
        default: '0.0.0'
      createRelease:
        description: 'Create a release'
        type: boolean
        default: false
  workflow_call:
    inputs:
      createRelease:
        description: 'Create a release'
        type: boolean
        default: false


jobs:
  run-gitversion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.SemVer }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id:   gitversion
        uses: gittools/actions/gitversion/execute@v0

  build-buildroot-images:
    strategy:
      matrix:
        image:
          - OS: lakka
            DOWNLOAD_URL: "https://nightly.builds.lakka.tv/5.x/2024-05-02/RPi4.aarch64/Lakka-RPi4.aarch64-5.x-20240502-2f60c70.img.gz"
            COMPRESSED_IMAGE_NAME: "Lakka-RPi4.aarch64-5.x-20240502-2f60c70.img.gz"
            IMAGE_NAME: "Lakka-RPi4.aarch64-5.x-20240502-2f60c70.img"
            CHECKSUM_TYPE: "sha256"
            PSPI_IMAGE_NAME: "Lakka5.0-CM4-PSPi6-v${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}.img.gz"
            VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}
          - OS: lakka
            DOWNLOAD_URL: "https://nightly.builds.lakka.tv/5.x/2024-05-02/RPi3.aarch64/Lakka-RPi3.aarch64-5.x-20240502-2f60c70.img.gz"
            COMPRESSED_IMAGE_NAME: "Lakka-RPi3.aarch64-5.x-20240502-2f60c70.img.gz"
            IMAGE_NAME: "Lakka-RPi3.aarch64-5.x-20240502-2f60c70.img"
            CHECKSUM_TYPE: "sha256"
            PSPI_IMAGE_NAME: "Lakka5.0-Zero2-PSPi6-v${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}.img.gz"
            VERSION: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.version || needs.run-gitversion.outputs.version }}
    runs-on: ubuntu-latest
    continue-on-error: true
    needs:
      - run-gitversion
    steps:
      - uses: actions/checkout@v4

      - name: Build & Publish Images
        uses: ./.github/actions/build-buildroot-image
        with:
          createRelease: ${{ inputs.createRelease }}
          os: ${{ matrix.image.OS }}
          download_url: ${{ matrix.image.DOWNLOAD_URL }}
          compressed_image_name: ${{ matrix.image.COMPRESSED_IMAGE_NAME }}
          image_name: ${{ matrix.image.IMAGE_NAME }}
          pspi_image_name: ${{ matrix.image.PSPI_IMAGE_NAME }}
          version: ${{ matrix.image.VERSION }}
          checksum_type: ${{ matrix.image.CHECKSUM_TYPE }}
