name: Build ATmega Firmware

on:
  workflow_call:
  push:
    paths:
      - 'atmega/firmware/**'
  pull_request:
    paths:
      - 'atmega/firmware/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install AVR toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends gcc-avr binutils-avr avr-libc

      - name: Install arduino-cli
        uses: arduino/setup-arduino-cli@v2

      - name: Install Arduino AVR core
        run: arduino-cli core install arduino:avr

      - name: Build
        run: |
          cd atmega/firmware
          make all

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: atmega-firmware
          path: atmega/firmware/firmware.hex
